(function () {
  "use strict";

  var translations = {
    en: {
      title: "Your account | Healthy Little Minds", description: "Create or manage your Healthy Little Minds account and library access.",
      brandLabel: "Healthy Little Minds public homepage", back: "Back to public resources", kicker: "Your account",
      heading: "One gentle place for your library.", intro: "Create an adult account or log in to connect your Healthy Little Minds purchase. Children do not need their own email address or account.",
      pointFree: "Free resources remain available without signing in.", pointEmail: "Use the same email address used during Payhip checkout.", pointSecure: "Your password is handled securely by Supabase Auth.",
      cardLabel: "Account access", tabsLabel: "Account actions", login: "Log in", signup: "Create account", welcome: "Welcome back",
      loginIntro: "Log in with your personal account to continue to your library.", email: "Email", password: "Password", forgot: "Forgot password?", resend: "Resend confirmation",
      signupHeading: "Create your account", signupIntro: "Use an adult’s email address, preferably the same one used at checkout.", name: "Your name", accountType: "I’m using Healthy Little Minds as",
      parent: "A parent or caregiver", educator: "An educator", createPassword: "Create a password", passwordNote: "Use at least eight characters and avoid reusing a password from another website.",
      recoveryHeading: "Choose a new password", recoveryIntro: "Use at least eight characters and choose something you do not use on another website.", newPassword: "New password", savePassword: "Save new password",
      checking: "Checking access…", hello: "Hello,", member: "Member", yourAccount: "your account", signedIn: "Signed in as", openLibrary: "Open member library", purchase: "Get full access", refresh: "Check access again", logout: "Log out",
      supportBefore: "Need help connecting an earlier purchase?", supportLink: "Contact support", supportAfter: "without sending payment-card details or a password.", terms: "Terms and conditions",
      activeBadge: "Full library access active", activeDescription: "Access confirmed — opening your member library…", inactiveBadge: "Account ready — access not connected", inactiveDescription: "If you already purchased, make sure this is the same email used at Payhip and check access again.",
      checkingAccount: "Checking your account…", wait: "Please wait…", signedOut: "Log in to open the member library.", emailUnconfirmed: "Confirm your email before opening the member library.", accessRequired: "Your account is ready, but full-library access is not connected yet.", accountUnavailable: "This account cannot currently open the member library. Contact support if you need help.", checkFailed: "We could not check your account. Please try again.",
      invalidLogin: "The email or password was not correct. Please try again or reset your password.", confirmEmail: "Please confirm your email before logging in. You can resend the confirmation below.", alreadyRegistered: "If an account already exists for this email, you can log in or reset the password.", shortPassword: "Choose a password with at least eight characters.", tooMany: "Too many attempts were made. Please wait a little while and try again.", genericError: "We could not complete that request. Please check your connection and try again.",
      signupSent: "Check your email to confirm your account. Return here after selecting the confirmation link.", enterEmailForgot: "Enter your email above, then select Forgot password again.", resetSent: "If an account is associated with that email, a password-reset message will arrive shortly.", enterEmailResend: "Enter your email above, then select Resend confirmation again.", resendSent: "If the account still needs confirmation, a new message will arrive shortly. Check Spam or Junk too.", passwordUpdated: "Your password has been updated. Your account is ready.", servicesPreparing: "Account services are being prepared. Please return to the main page and try again later."
    },
    ja: {
      title: "アカウント | Healthy Little Minds", description: "Healthy Little Minds のアカウントとライブラリー利用権を管理します。", brandLabel: "Healthy Little Minds 公開ホームページ", back: "公開リソースへ戻る", kicker: "あなたのアカウント", heading: "ライブラリーにつながる、やさしい場所。", intro: "大人の方がアカウントを作成またはログインして、Healthy Little Minds の購入情報を連携してください。お子さま自身のメールアドレスやアカウントは必要ありません。", pointFree: "無料リソースはログインなしで利用できます。", pointEmail: "Payhipで購入したときと同じメールアドレスを使用してください。", pointSecure: "パスワードは Supabase Auth が安全に管理します。", cardLabel: "アカウントアクセス", tabsLabel: "アカウント操作", login: "ログイン", signup: "アカウント作成", welcome: "おかえりなさい", loginIntro: "個人アカウントでログインしてライブラリーへ進みます。", email: "メールアドレス", password: "パスワード", forgot: "パスワードを忘れた場合", resend: "確認メールを再送", signupHeading: "アカウントを作成", signupIntro: "大人の方のメールアドレスを使用してください。購入時と同じアドレスをおすすめします。", name: "お名前", accountType: "Healthy Little Minds の利用目的", parent: "保護者・養育者", educator: "教育者", createPassword: "パスワードを作成", passwordNote: "8文字以上で、他のサイトと異なるパスワードを使用してください。", recoveryHeading: "新しいパスワードを設定", recoveryIntro: "8文字以上で、他のサイトでは使っていないものを選んでください。", newPassword: "新しいパスワード", savePassword: "新しいパスワードを保存", checking: "利用権を確認中…", hello: "こんにちは、", member: "メンバー", yourAccount: "あなたのアカウント", signedIn: "ログイン中：", openLibrary: "メンバーライブラリーを開く", purchase: "フルアクセスを購入", refresh: "利用権を再確認", logout: "ログアウト", supportBefore: "以前の購入との連携でお困りですか？", supportLink: "サポートへ連絡", supportAfter: "カード情報やパスワードは送らないでください。", terms: "利用規約", activeBadge: "ライブラリーのフルアクセスが有効です", activeDescription: "利用権を確認しました。ライブラリーを開いています…", inactiveBadge: "アカウント作成済み — 利用権は未連携", inactiveDescription: "購入済みの場合は、Payhipで使用したものと同じメールアドレスか確認し、利用権を再確認してください。", checkingAccount: "アカウントを確認中…", wait: "お待ちください…", signedOut: "メンバーライブラリーを開くにはログインしてください。", emailUnconfirmed: "ライブラリーを開く前にメールアドレスを確認してください。", accessRequired: "アカウントは利用できますが、ライブラリーの利用権がまだ連携されていません。", accountUnavailable: "現在このアカウントではライブラリーを開けません。サポートへお問い合わせください。", checkFailed: "アカウントを確認できませんでした。もう一度お試しください。", invalidLogin: "メールアドレスまたはパスワードが正しくありません。もう一度試すか、パスワードを再設定してください。", confirmEmail: "ログイン前に確認メールを開いてください。下から確認メールを再送できます。", alreadyRegistered: "このメールアドレスのアカウントがある場合は、ログインまたはパスワード再設定をお試しください。", shortPassword: "8文字以上のパスワードを入力してください。", tooMany: "試行回数が多すぎます。しばらく待ってからお試しください。", genericError: "処理を完了できませんでした。接続を確認してもう一度お試しください。", signupSent: "確認メールを送信しました。メール内の確認リンクを選択して、こちらへ戻ってください。", enterEmailForgot: "上にメールアドレスを入力してから、もう一度「パスワードを忘れた場合」を選択してください。", resetSent: "該当するアカウントがある場合、パスワード再設定メールが届きます。", enterEmailResend: "上にメールアドレスを入力してから、確認メールを再送してください。", resendSent: "確認が必要な場合は新しいメールが届きます。迷惑メールフォルダーもご確認ください。", passwordUpdated: "パスワードを更新しました。アカウントを利用できます。", servicesPreparing: "アカウントサービスを準備中です。メインページへ戻り、後でもう一度お試しください。"
    },
    ko: {
      title: "계정 | Healthy Little Minds", description: "Healthy Little Minds 계정과 라이브러리 이용 권한을 관리하세요.", brandLabel: "Healthy Little Minds 공개 홈페이지", back: "공개 자료로 돌아가기", kicker: "내 계정", heading: "라이브러리를 위한 편안한 공간.", intro: "성인 계정을 만들거나 로그인하여 Healthy Little Minds 구매 내역을 연결하세요. 어린이는 별도의 이메일 주소나 계정이 필요하지 않습니다.", pointFree: "무료 자료는 로그인 없이 계속 이용할 수 있습니다.", pointEmail: "Payhip 결제에 사용한 이메일 주소를 사용해 주세요.", pointSecure: "비밀번호는 Supabase Auth에서 안전하게 관리합니다.", cardLabel: "계정 이용", tabsLabel: "계정 작업", login: "로그인", signup: "계정 만들기", welcome: "다시 만나 반가워요", loginIntro: "개인 계정으로 로그인하여 라이브러리로 이동하세요.", email: "이메일", password: "비밀번호", forgot: "비밀번호를 잊으셨나요?", resend: "확인 이메일 다시 보내기", signupHeading: "계정 만들기", signupIntro: "성인의 이메일 주소를 사용하세요. 결제에 사용한 주소와 같으면 가장 좋습니다.", name: "이름", accountType: "Healthy Little Minds 이용 유형", parent: "부모 또는 보호자", educator: "교육자", createPassword: "비밀번호 만들기", passwordNote: "8자 이상을 사용하고 다른 웹사이트의 비밀번호를 재사용하지 마세요.", recoveryHeading: "새 비밀번호 선택", recoveryIntro: "8자 이상이며 다른 웹사이트에서 사용하지 않는 비밀번호를 선택하세요.", newPassword: "새 비밀번호", savePassword: "새 비밀번호 저장", checking: "이용 권한 확인 중…", hello: "안녕하세요,", member: "회원", yourAccount: "내 계정", signedIn: "로그인 이메일:", openLibrary: "회원 라이브러리 열기", purchase: "전체 이용권 구매", refresh: "이용 권한 다시 확인", logout: "로그아웃", supportBefore: "이전 구매 연결에 도움이 필요하신가요?", supportLink: "지원팀에 문의", supportAfter: "카드 정보나 비밀번호는 보내지 마세요.", terms: "이용 약관", activeBadge: "전체 라이브러리 이용 권한 활성화", activeDescription: "이용 권한을 확인했습니다. 라이브러리를 여는 중입니다…", inactiveBadge: "계정 준비 완료 — 이용 권한 미연결", inactiveDescription: "이미 구매했다면 Payhip 결제 이메일과 같은지 확인한 뒤 이용 권한을 다시 확인하세요.", checkingAccount: "계정을 확인하는 중…", wait: "잠시만 기다려 주세요…", signedOut: "회원 라이브러리를 열려면 로그인하세요.", emailUnconfirmed: "라이브러리를 열기 전에 이메일을 확인하세요.", accessRequired: "계정은 준비되었지만 전체 라이브러리 이용 권한이 아직 연결되지 않았습니다.", accountUnavailable: "현재 이 계정으로 라이브러리를 열 수 없습니다. 지원팀에 문의해 주세요.", checkFailed: "계정을 확인할 수 없습니다. 다시 시도해 주세요.", invalidLogin: "이메일 또는 비밀번호가 올바르지 않습니다. 다시 시도하거나 비밀번호를 재설정하세요.", confirmEmail: "로그인 전에 이메일을 확인하세요. 아래에서 확인 이메일을 다시 보낼 수 있습니다.", alreadyRegistered: "이 이메일로 계정이 이미 있다면 로그인하거나 비밀번호를 재설정하세요.", shortPassword: "8자 이상의 비밀번호를 선택하세요.", tooMany: "시도 횟수가 너무 많습니다. 잠시 후 다시 시도하세요.", genericError: "요청을 완료할 수 없습니다. 연결을 확인하고 다시 시도하세요.", signupSent: "확인 이메일을 확인하세요. 이메일의 확인 링크를 선택한 뒤 여기로 돌아오세요.", enterEmailForgot: "위에 이메일을 입력한 뒤 비밀번호 찾기를 다시 선택하세요.", resetSent: "해당 이메일의 계정이 있다면 곧 비밀번호 재설정 이메일이 도착합니다.", enterEmailResend: "위에 이메일을 입력한 뒤 확인 이메일 다시 보내기를 선택하세요.", resendSent: "계정 확인이 필요하면 새 이메일이 도착합니다. 스팸함도 확인하세요.", passwordUpdated: "비밀번호가 업데이트되었습니다. 계정을 사용할 수 있습니다.", servicesPreparing: "계정 서비스를 준비 중입니다. 메인 페이지로 돌아가 나중에 다시 시도하세요."
    },
    "zh-cn": {
      title: "账户 | Healthy Little Minds", description: "创建或管理 Healthy Little Minds 账户和资源库访问权限。", brandLabel: "Healthy Little Minds 公开主页", back: "返回公开资源", kicker: "您的账户", heading: "一个温馨的资源库空间。", intro: "请由成人创建账户或登录，以关联 Healthy Little Minds 购买记录。儿童不需要自己的电子邮箱或账户。", pointFree: "免费资源无需登录即可继续使用。", pointEmail: "请使用 Payhip 付款时填写的同一电子邮箱。", pointSecure: "您的密码由 Supabase Auth 安全管理。", cardLabel: "账户访问", tabsLabel: "账户操作", login: "登录", signup: "创建账户", welcome: "欢迎回来", loginIntro: "登录个人账户，继续进入您的资源库。", email: "电子邮箱", password: "密码", forgot: "忘记密码？", resend: "重新发送确认邮件", signupHeading: "创建账户", signupIntro: "请使用成人的电子邮箱，最好与付款时使用的邮箱一致。", name: "您的姓名", accountType: "我使用 Healthy Little Minds 的身份", parent: "家长或照护者", educator: "教育工作者", createPassword: "创建密码", passwordNote: "请使用至少八个字符，并避免使用其他网站的密码。", recoveryHeading: "设置新密码", recoveryIntro: "请使用至少八个字符，并选择未在其他网站使用的密码。", newPassword: "新密码", savePassword: "保存新密码", checking: "正在检查访问权限…", hello: "您好，", member: "会员", yourAccount: "您的账户", signedIn: "登录邮箱：", openLibrary: "打开会员资源库", purchase: "获取完整访问权限", refresh: "重新检查访问权限", logout: "退出登录", supportBefore: "需要帮助关联以前的购买记录？", supportLink: "联系支持", supportAfter: "请勿发送银行卡信息或密码。", terms: "条款与条件", activeBadge: "完整资源库访问已启用", activeDescription: "访问权限已确认，正在打开会员资源库…", inactiveBadge: "账户已就绪 — 访问权限尚未关联", inactiveDescription: "如果您已购买，请确认此邮箱与 Payhip 付款邮箱一致，然后重新检查访问权限。", checkingAccount: "正在检查您的账户…", wait: "请稍候…", signedOut: "请登录以打开会员资源库。", emailUnconfirmed: "打开资源库前，请先确认您的电子邮箱。", accessRequired: "您的账户已就绪，但完整资源库访问权限尚未关联。", accountUnavailable: "此账户目前无法打开资源库。如需帮助，请联系支持。", checkFailed: "无法检查您的账户，请重试。", invalidLogin: "电子邮箱或密码不正确。请重试或重置密码。", confirmEmail: "登录前请先确认电子邮箱。您可以在下方重新发送确认邮件。", alreadyRegistered: "如果此邮箱已有账户，您可以登录或重置密码。", shortPassword: "请选择至少八个字符的密码。", tooMany: "尝试次数过多，请稍后重试。", genericError: "无法完成此请求。请检查网络连接后重试。", signupSent: "请查看确认邮件。点击邮件中的确认链接后返回此页面。", enterEmailForgot: "请先在上方输入电子邮箱，然后再次选择“忘记密码”。", resetSent: "如果该邮箱关联了账户，密码重置邮件将很快送达。", enterEmailResend: "请先在上方输入电子邮箱，然后重新发送确认邮件。", resendSent: "如果账户仍需确认，新的邮件将很快送达。也请检查垃圾邮件文件夹。", passwordUpdated: "密码已更新，您的账户已就绪。", servicesPreparing: "账户服务正在准备中。请返回主页，稍后重试。"
    },
    "zh-tw": {
      title: "帳戶 | Healthy Little Minds", description: "建立或管理 Healthy Little Minds 帳戶與資源庫存取權。", brandLabel: "Healthy Little Minds 公開首頁", back: "返回公開資源", kicker: "您的帳戶", heading: "一個溫柔的資源庫空間。", intro: "請由成人建立帳戶或登入，以連結 Healthy Little Minds 的購買記錄。兒童不需要自己的電子郵件或帳戶。", pointFree: "免費資源無需登入即可繼續使用。", pointEmail: "請使用 Payhip 付款時填寫的同一電子郵件。", pointSecure: "您的密碼由 Supabase Auth 安全管理。", cardLabel: "帳戶存取", tabsLabel: "帳戶操作", login: "登入", signup: "建立帳戶", welcome: "歡迎回來", loginIntro: "登入個人帳戶，繼續前往您的資源庫。", email: "電子郵件", password: "密碼", forgot: "忘記密碼？", resend: "重新傳送確認信", signupHeading: "建立帳戶", signupIntro: "請使用成人的電子郵件，最好與付款時使用的信箱一致。", name: "您的姓名", accountType: "我使用 Healthy Little Minds 的身分", parent: "家長或照顧者", educator: "教育工作者", createPassword: "建立密碼", passwordNote: "請使用至少八個字元，並避免使用其他網站的密碼。", recoveryHeading: "設定新密碼", recoveryIntro: "請使用至少八個字元，並選擇未在其他網站使用的密碼。", newPassword: "新密碼", savePassword: "儲存新密碼", checking: "正在檢查存取權…", hello: "您好，", member: "會員", yourAccount: "您的帳戶", signedIn: "登入信箱：", openLibrary: "開啟會員資源庫", purchase: "取得完整存取權", refresh: "重新檢查存取權", logout: "登出", supportBefore: "需要協助連結之前的購買記錄？", supportLink: "聯絡支援", supportAfter: "請勿傳送信用卡資料或密碼。", terms: "條款與細則", activeBadge: "完整資源庫存取已啟用", activeDescription: "存取權已確認，正在開啟會員資源庫…", inactiveBadge: "帳戶已就緒 — 存取權尚未連結", inactiveDescription: "如果您已購買，請確認此信箱與 Payhip 付款信箱相同，然後重新檢查存取權。", checkingAccount: "正在檢查您的帳戶…", wait: "請稍候…", signedOut: "請登入以開啟會員資源庫。", emailUnconfirmed: "開啟資源庫前，請先確認您的電子郵件。", accessRequired: "您的帳戶已就緒，但完整資源庫存取權尚未連結。", accountUnavailable: "此帳戶目前無法開啟資源庫。如需協助，請聯絡支援。", checkFailed: "無法檢查您的帳戶，請再試一次。", invalidLogin: "電子郵件或密碼不正確。請重試或重設密碼。", confirmEmail: "登入前請先確認電子郵件。您可以在下方重新傳送確認信。", alreadyRegistered: "如果此信箱已有帳戶，您可以登入或重設密碼。", shortPassword: "請選擇至少八個字元的密碼。", tooMany: "嘗試次數過多，請稍後再試。", genericError: "無法完成此要求。請檢查網路連線後重試。", signupSent: "請查看確認信。點選信中的確認連結後返回此頁面。", enterEmailForgot: "請先在上方輸入電子郵件，然後再次選擇「忘記密碼」。", resetSent: "如果該信箱連結了帳戶，密碼重設郵件將很快送達。", enterEmailResend: "請先在上方輸入電子郵件，然後重新傳送確認信。", resendSent: "如果帳戶仍需確認，新的郵件將很快送達。也請檢查垃圾郵件匣。", passwordUpdated: "密碼已更新，您的帳戶已就緒。", servicesPreparing: "帳戶服務正在準備中。請返回首頁，稍後再試。"
    }
  };

  var locale = window.HLMRouting ? window.HLMRouting.locale() : "en";
  var copy = translations[locale] || translations.en;
  var visualCopy = {
    en: ["Made for caring adults", "Stories and tools for growing minds.", "Your library is just a step away"],
    ja: ["大切に寄り添う大人の方へ", "育つ心のための物語とツール。", "ライブラリーまで、あと一歩です"],
    ko: ["아이를 아끼는 어른을 위해", "성장하는 마음을 위한 이야기와 도구.", "라이브러리까지 한 걸음 남았어요"],
    "zh-cn": ["为关爱孩子的成人而设计", "陪伴心灵成长的故事与工具。", "距离您的资源库只差一步"],
    "zh-tw": ["為關心孩子的成人而設計", "陪伴心靈成長的故事與工具。", "距離您的資源庫只差一步"]
  }[locale] || ["Made for caring adults", "Stories and tools for growing minds.", "Your library is just a step away"];

  function t(key) { return copy[key] || translations.en[key] || key; }
  function text(selector, key) { var node = document.querySelector(selector); if (node) node.textContent = t(key); }
  function label(selector, key) { var node = document.querySelector(selector); if (node && node.firstChild) node.firstChild.nodeValue = t(key) + "\n              "; }

  function apply() {
    document.documentElement.lang = locale === "zh-cn" ? "zh-CN" : locale === "zh-tw" ? "zh-Hant" : locale;
    document.title = t("title");
    var meta = document.querySelector('meta[name="description"]'); if (meta) meta.content = t("description");
    var brand = document.querySelector(".account-brand"); if (brand) brand.setAttribute("aria-label", t("brandLabel"));
    text(".account-back", "back"); text(".account-kicker", "kicker"); text("#accountTitle", "heading"); text(".account-intro > p:not(.account-kicker)", "intro");
    text(".account-points li:nth-child(1)", "pointFree"); text(".account-points li:nth-child(2)", "pointEmail"); text(".account-points li:nth-child(3)", "pointSecure");
    var card = document.querySelector(".account-card"); if (card) card.setAttribute("aria-label", t("cardLabel"));
    var tabs = document.querySelector(".account-tabs"); if (tabs) tabs.setAttribute("aria-label", t("tabsLabel"));
    text('[data-account-tab="login"]', "login"); text('[data-account-tab="signup"]', "signup");
    text('[data-account-panel="login"] h2', "welcome"); text('[data-account-panel="login"] > p', "loginIntro");
    label('#loginForm label:nth-of-type(1)', "email"); label('#loginForm label:nth-of-type(2)', "password"); text('#loginForm button[type="submit"]', "login"); text("#forgotPassword", "forgot"); text("#resendConfirmation", "resend");
    text('[data-account-panel="signup"] h2', "signupHeading"); text('[data-account-panel="signup"] > p', "signupIntro");
    label('#signupForm label:nth-of-type(1)', "name"); label('#signupForm label:nth-of-type(2)', "accountType"); label('#signupForm label:nth-of-type(3)', "email"); label('#signupForm label:nth-of-type(4)', "createPassword");
    text('#signupForm option[value="parent"]', "parent"); text('#signupForm option[value="educator"]', "educator"); text("#passwordNote", "passwordNote"); text('#signupForm button[type="submit"]', "signup");
    text('[data-account-panel="recovery"] h2', "recoveryHeading"); text('[data-account-panel="recovery"] > p', "recoveryIntro"); label('#recoveryForm label', "newPassword"); text('#recoveryForm button[type="submit"]', "savePassword");
    text("#accessBadge", "checking"); text("#signedInLabel", "signedIn"); text("#openLibraryButton", "openLibrary"); text("#purchaseButton", "purchase"); text("#refreshAccess", "refresh"); text("#signOutButton", "logout");
    var visualEyebrow = document.querySelector("#visualEyebrow"); if (visualEyebrow) visualEyebrow.textContent = visualCopy[0];
    var visualText = document.querySelector("#visualText"); if (visualText) visualText.textContent = visualCopy[1];
    var cardWelcome = document.querySelector("#cardWelcome"); if (cardWelcome) cardWelcome.textContent = visualCopy[2];
    text("#supportBefore", "supportBefore"); text("#supportLink", "supportLink"); text("#supportAfter", "supportAfter"); text("#termsLink", "terms");
    var publicHome = window.HLMRouting.page("index.html"); if (brand) brand.href = publicHome; var back = document.querySelector(".account-back"); if (back) back.href = publicHome;
    var support = document.querySelector("#supportLink"); if (support) support.href = "/contact.html";
    var currentParams = new URLSearchParams(window.location.search);
    document.querySelectorAll("[data-account-locale]").forEach(function (link) {
      var targetLocale = link.dataset.accountLocale;
      var params = new URLSearchParams(currentParams);
      if (targetLocale === "en") params.delete("locale"); else params.set("locale", targetLocale);
      link.href = "/account.html" + (params.toString() ? "?" + params.toString() : "");
      if (targetLocale === locale) link.setAttribute("aria-current", "page"); else link.removeAttribute("aria-current");
    });
  }

  apply();
  window.HLMAccountI18n = { apply: apply, locale: locale, t: t };
})();
